import type {
  Category,
  DashboardStats,
  Order,
  Product,
  Vendor,
} from "./types";

export const mockCategories: Category[] = [
  { id: "cat-electronics", name: "Electronics", slug: "electronics", emoji: "📱" },
  { id: "cat-fashion", name: "Fashion", slug: "fashion", emoji: "👕" },
  { id: "cat-home", name: "Home & Living", slug: "home-living", emoji: "🏠" },
  { id: "cat-groceries", name: "Groceries", slug: "groceries", emoji: "🛒" },
  { id: "cat-beauty", name: "Beauty", slug: "beauty", emoji: "✨" },
  { id: "cat-sports", name: "Sports & Outdoors", slug: "sports", emoji: "⚽" },
];

const img = (seed: string, size = 800) => `https://picsum.photos/seed/${seed}/${size}/${size}`;

export const mockVendors: Vendor[] = [
  {
    id: "vendor-1",
    name: "Colombo Digital Hub",
    slug: "colombo-digital-hub",
    tagline: "Gadgets that keep you ahead",
    description:
      "Colombo Digital Hub sources the latest electronics and gadgets from trusted global brands, with a focus on warranty-backed products and fast island-wide delivery.",
    logo: img("vendor-1-logo", 200),
    cover: img("vendor-1-cover", 1200),
    location: "Colombo 03",
    rating: 4.7,
    reviewCount: 342,
    joinedAt: "2024-03-12",
    productCount: 4,
    status: "active",
  },
  {
    id: "vendor-2",
    name: "Ceylon Threads",
    slug: "ceylon-threads",
    tagline: "Handcrafted apparel with a local touch",
    description:
      "Ceylon Threads is a family-run studio in Galle producing contemporary clothing from premium Sri Lankan fabrics. Every piece is cut, sewn and finished by hand.",
    logo: img("vendor-2-logo", 200),
    cover: img("vendor-2-cover", 1200),
    location: "Galle",
    rating: 4.9,
    reviewCount: 187,
    joinedAt: "2023-11-02",
    productCount: 3,
    status: "active",
  },
  {
    id: "vendor-3",
    name: "Island Home",
    slug: "island-home",
    tagline: "Comfort for every corner of your home",
    description:
      "From aromatic candles to furniture, Island Home curates practical, beautiful products for modern Sri Lankan households at honest prices.",
    logo: img("vendor-3-logo", 200),
    cover: img("vendor-3-cover", 1200),
    location: "Kandy",
    rating: 4.5,
    reviewCount: 96,
    joinedAt: "2024-06-20",
    productCount: 3,
    status: "active",
  },
  {
    id: "vendor-4",
    name: "Fresh Market SL",
    slug: "fresh-market-sl",
    tagline: "Farm to doorstep in 24 hours",
    description:
      "Fresh Market SL partners with smallholder farmers across the island to deliver certified organic groceries, freshly harvested and packed daily.",
    logo: img("vendor-4-logo", 200),
    cover: img("vendor-4-cover", 1200),
    location: "Dambulla",
    rating: 4.6,
    reviewCount: 521,
    joinedAt: "2023-08-15",
    productCount: 2,
    status: "active",
  },
];

export const mockProducts: Product[] = [
  {
    id: "p-1",
    name: "Aurora Wireless Headphones",
    slug: "aurora-wireless-headphones",
    shortDescription: "Active noise cancelling over-ear headphones with 40h battery life.",
    longDescription:
      "Immerse yourself in studio-grade sound with the Aurora Wireless Headphones. Adaptive noise cancellation, plush memory-foam earcups and 40 hours of playtime make them perfect for long flights, deep work sessions and everything in between.",
    price: 68500,
    compareAtPrice: 82000,
    images: [img("aurora-headphones"), img("aurora-headphones-2"), img("aurora-headphones-3")],
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    vendorId: "vendor-1",
    vendorName: "Colombo Digital Hub",
    stock: 24,
    soldCount: 312,
    rating: 4.8,
    reviewCount: 210,
    isFeatured: true,
    tags: ["audio", "wireless", "noise-cancelling"],
  },
  {
    id: "p-2",
    name: "Swift 65W GaN Charger",
    slug: "swift-65w-gan-charger",
    shortDescription: "Ultra-compact dual-port charger for phones, tablets and laptops.",
    longDescription:
      "Charge everything from one pocket-sized brick. The Swift 65W GaN charger delivers fast, efficient power over two USB-C ports and one USB-A port, with full international safety certifications.",
    price: 12500,
    images: [img("gan-charger"), img("gan-charger-2")],
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    vendorId: "vendor-1",
    vendorName: "Colombo Digital Hub",
    stock: 60,
    soldCount: 428,
    rating: 4.5,
    reviewCount: 88,
    isFeatured: false,
    tags: ["charging", "travel", "gan"],
  },
  {
    id: "p-3",
    name: "Nimbus Smart Watch",
    slug: "nimbus-smart-watch",
    shortDescription: "AMOLED display, heart-rate tracking and 10-day battery.",
    longDescription:
      "The Nimbus Smart Watch blends a vibrant AMOLED display with serious fitness tracking — heart rate, SpO2, sleep and 100+ workout modes — all wrapped in a lightweight aluminium body with a 10-day battery.",
    price: 45000,
    compareAtPrice: 56000,
    images: [img("smart-watch"), img("smart-watch-2"), img("smart-watch-3")],
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    vendorId: "vendor-1",
    vendorName: "Colombo Digital Hub",
    stock: 15,
    soldCount: 197,
    rating: 4.6,
    reviewCount: 134,
    isFeatured: true,
    tags: ["wearables", "fitness", "smartwatch"],
  },
  {
    id: "p-4",
    name: "Linen Resort Shirt",
    slug: "linen-resort-shirt",
    shortDescription: "Breathable 100% linen shirt in a relaxed fit.",
    longDescription:
      "Cut from washed European linen, this resort shirt keeps you cool in tropical heat while looking sharp. Relaxed fit, mother-of-pearl buttons and a chest pocket — a wardrobe staple for island living.",
    price: 8900,
    compareAtPrice: 11500,
    images: [img("linen-shirt"), img("linen-shirt-2")],
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    vendorId: "vendor-2",
    vendorName: "Ceylon Threads",
    stock: 40,
    soldCount: 254,
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    tags: ["linen", "summer", "shirt"],
  },
  {
    id: "p-5",
    name: "Batik Sarong",
    slug: "batik-sarong",
    shortDescription: "Hand-dyed batik sarong, made to order.",
    longDescription:
      "Each batik sarong is hand-dyed in Galle using traditional wax-resist techniques and natural pigments. No two pieces are identical — a genuine piece of Sri Lankan craftsmanship for lounging or dressing up.",
    price: 5400,
    images: [img("batik-sarong"), img("batik-sarong-2")],
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    vendorId: "vendor-2",
    vendorName: "Ceylon Threads",
    stock: 18,
    soldCount: 138,
    rating: 5.0,
    reviewCount: 42,
    isFeatured: false,
    tags: ["batik", "handmade", "local"],
  },
  {
    id: "p-6",
    name: "Canvas Tote — Coconut Grove",
    slug: "canvas-tote-coconut-grove",
    shortDescription: "Heavyweight canvas tote with screen-printed art.",
    longDescription:
      "A sturdy 12oz canvas tote featuring original screen-printed artwork inspired by a southern coconut grove. Big enough for the market run, strong enough for your books.",
    price: 3200,
    images: [img("canvas-tote"), img("canvas-tote-2")],
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    vendorId: "vendor-2",
    vendorName: "Ceylon Threads",
    stock: 75,
    soldCount: 486,
    rating: 4.7,
    reviewCount: 63,
    isFeatured: false,
    tags: ["tote", "canvas", "eco"],
  },
  {
    id: "p-7",
    name: "Cinnamon Cedar Candle",
    slug: "cinnamon-cedar-candle",
    shortDescription: "Hand-poured soy candle, 45h burn time.",
    longDescription:
      "Hand-poured in small batches from soy wax, this candle blends warm cinnamon bark with earthy cedarwood. Made with cotton wicks and a clean burn of up to 45 hours.",
    price: 2600,
    compareAtPrice: 3200,
    images: [img("candle"), img("candle-2")],
    categoryId: "cat-home",
    categoryName: "Home & Living",
    vendorId: "vendor-3",
    vendorName: "Island Home",
    stock: 90,
    soldCount: 612,
    rating: 4.8,
    reviewCount: 205,
    isFeatured: true,
    tags: ["candle", "aroma", "home"],
  },
  {
    id: "p-8",
    name: "Teak Serving Board",
    slug: "teak-serving-board",
    shortDescription: "Reclaimed teak board for serving and chopping.",
    longDescription:
      "Crafted from reclaimed railway teak, this serving board brings warmth to cheese platters and casual dining. Oiled with food-safe coconut oil and finished by hand in Kandy.",
    price: 7800,
    images: [img("teak-board"), img("teak-board-2")],
    categoryId: "cat-home",
    categoryName: "Home & Living",
    vendorId: "vendor-3",
    vendorName: "Island Home",
    stock: 12,
    soldCount: 94,
    rating: 4.6,
    reviewCount: 31,
    isFeatured: false,
    tags: ["teak", "kitchen", "reclaimed"],
  },
  {
    id: "p-9",
    name: "Rattan Lounge Chair",
    slug: "rattan-lounge-chair",
    shortDescription: "Handwoven rattan chair with plush cushion.",
    longDescription:
      "A statement piece woven by village artisans. The Rattan Lounge Chair pairs a natural handwoven frame with a removable, washable cushion — timeless comfort for veranda evenings.",
    price: 47500,
    compareAtPrice: 59000,
    images: [img("rattan-chair"), img("rattan-chair-2"), img("rattan-chair-3")],
    categoryId: "cat-home",
    categoryName: "Home & Living",
    vendorId: "vendor-3",
    vendorName: "Island Home",
    stock: 6,
    soldCount: 57,
    rating: 4.9,
    reviewCount: 27,
    isFeatured: true,
    tags: ["furniture", "rattan", "handmade"],
  },
  {
    id: "p-10",
    name: "Organic Ceylon Tea Sampler",
    slug: "organic-ceylon-tea-sampler",
    shortDescription: "5 estate teas from the hill country, 250g.",
    longDescription:
      "A curated journey through Sri Lanka's tea country: black, green and silver tips from five high-grown estates. Certified organic, packed in biodegradable pouches within 48 hours of plucking.",
    price: 4200,
    images: [img("tea-sampler"), img("tea-sampler-2")],
    categoryId: "cat-groceries",
    categoryName: "Groceries",
    vendorId: "vendor-4",
    vendorName: "Fresh Market SL",
    stock: 120,
    soldCount: 1043,
    rating: 4.9,
    reviewCount: 318,
    isFeatured: true,
    tags: ["tea", "organic", "gift"],
  },
  {
    id: "p-11",
    name: "King Coconut Set (6)",
    slug: "king-coconut-set-6",
    shortDescription: "Farm-fresh king coconuts, delivered chilled.",
    longDescription:
      "Six tender king coconuts harvested at dawn from certified farms in Dambulla, delivered chilled the same day. Nature's electrolyte drink, straight to your doorstep.",
    price: 1800,
    images: [img("king-coconut"), img("king-coconut-2")],
    categoryId: "cat-groceries",
    categoryName: "Groceries",
    vendorId: "vendor-4",
    vendorName: "Fresh Market SL",
    stock: 45,
    soldCount: 835,
    rating: 4.7,
    reviewCount: 429,
    isFeatured: false,
    tags: ["coconut", "fresh", "organic"],
  },
  {
    id: "p-12",
    name: "Riptide Fitness Bottle",
    slug: "riptide-fitness-bottle",
    shortDescription: "750ml insulated steel bottle, 24h cold.",
    longDescription:
      "Double-wall vacuum insulated steel keeps drinks cold for 24 hours or hot for 12. Leakproof, powder-coated and built for the gym, the trail or the daily commute.",
    price: 6500,
    compareAtPrice: 7900,
    images: [img("fitness-bottle"), img("fitness-bottle-2")],
    categoryId: "cat-sports",
    categoryName: "Sports & Outdoors",
    vendorId: "vendor-1",
    vendorName: "Colombo Digital Hub",
    stock: 55,
    soldCount: 341,
    rating: 4.6,
    reviewCount: 74,
    isFeatured: false,
    tags: ["bottle", "fitness", "insulated"],
  },
];

const daysAgo = (d: number) =>
  new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

export const mockOrders: Order[] = [
  {
    id: "o-1",
    number: "KD-10524",
    customerId: "customer-demo",
    customerName: "Sanduni Perera",
    email: "sanduni@example.com",
    items: [
      { productId: "p-1", name: "Aurora Wireless Headphones", image: img("aurora-headphones", 300), price: 68500, qty: 1 },
      { productId: "p-10", name: "Organic Ceylon Tea Sampler", image: img("tea-sampler", 300), price: 4200, qty: 2 },
    ],
    subtotal: 76900,
    shippingFee: 600,
    total: 77500,
    status: "delivered",
    placedAt: daysAgo(12),
    address: { line1: "24 Park Road", city: "Colombo 05", zip: "00500" },
  },
  {
    id: "o-2",
    number: "KD-10542",
    customerId: "customer-demo",
    customerName: "Sanduni Perera",
    email: "sanduni@example.com",
    items: [
      { productId: "p-4", name: "Linen Resort Shirt", image: img("linen-shirt", 300), price: 8900, qty: 1 },
      { productId: "p-6", name: "Canvas Tote — Coconut Grove", image: img("canvas-tote", 300), price: 3200, qty: 1 },
    ],
    subtotal: 12100,
    shippingFee: 400,
    total: 12500,
    status: "shipped",
    placedAt: daysAgo(3),
    address: { line1: "24 Park Road", city: "Colombo 05", zip: "00500" },
  },
  {
    id: "o-3",
    number: "KD-10558",
    customerId: "customer-demo",
    customerName: "Sanduni Perera",
    email: "sanduni@example.com",
    items: [
      { productId: "p-3", name: "Nimbus Smart Watch", image: img("smart-watch", 300), price: 45000, qty: 1 },
    ],
    subtotal: 45000,
    shippingFee: 600,
    total: 45600,
    status: "pending",
    placedAt: daysAgo(1),
    address: { line1: "24 Park Road", city: "Colombo 05", zip: "00500" },
  },
];

export const mockStats: DashboardStats = {
  revenue: 1863400,
  orders: 142,
  pendingOrders: 18,
  products: 12,
  customers: 356,
  avgOrderValue: 13122,
};
